##
## SonataBlockBundle configuration
##
#sonata_block:
#    default_contexts: [cms]
#    blocks:
#        sonata.admin.block.admin_list:
#            contexts:   [admin]
#
#        #sonata.admin_doctrine_orm.block.audit:
#        #    contexts:   [admin]
#
#        sonata.block.service.text:
#        sonata.block.service.action:
#        sonata.block.service.rss:
#
#        # Some specific block from the SonataMediaBundle
#        #sonata.media.block.media:
#        #sonata.media.block.gallery:
#        #sonata.media.block.feature_media:
#
##
## SonataMediaBundle configuration
##
#
# SonataMediaBundle configuration
#
#sonata_media:
#    default_context: default
#    db_driver: doctrine_orm
#    class:
#        media:              Sfynx\MediaBundle\Layers\Domain\Entity\Media
#        category:           Sfynx\ClassificationBundle\Entity\Category
#        gallery:            Sfynx\MediaBundle\Layers\Domain\Entity\Gallery
#        gallery_has_media:  Sfynx\MediaBundle\Layers\Domain\Entity\GalleryHasMedia
#    contexts:
#        sonata_collection:
#            providers:
#              - sonata.media.provider.image
#
#            formats:
#                preview: { width: 100, quality: 100}
#                wide:    { width: 820, quality: 100}
#
#        sonata_category:
#            providers:
#              - sonata.media.provider.image
#
#            formats:
#                preview: { width: 100, quality: 100}
#                wide:    { width: 820, quality: 100}
#        default:  # the default context is mandatory
#            download:
#                #strategy: sonata.media.security.session_strategy # a media can be downloaded only once per session.
#                strategy: sonata.media.security.public_strategy         # ROLE_USER
#                #strategy: sonata.media.security.superadmin_strategy  # ROLE_SUPER_ADMIN or ROLE_ADMIN
#                #strategy: sonata.media.security.public_strategy      # no restriction, files are public
#                #strategy: sonata.media.security.forbidden_strategy   # not possible to retrieve the original file
#                #strategy: sonata.media.security.connected_strategy   # IS_AUTHENTICATED_FULLY or IS_AUTHENTICATED_REMEMBERED
#                mode: http              # use php to send the file
#                #mode: X-Sendfile        # use the X-Sendfile flag (Apache + mod_xsendfile : https://tn123.org/mod_xsendfile/)
#                #mode: X-Accel-Redirect  # use the X-Accel-Redirect flag (Nginx : http://wiki.nginx.org/X-accel)
#            providers:
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
#                - sonata.media.provider.image
#                - sonata.media.provider.file
#
#            formats:
#                small: { width: 100 , quality: 70}
#                #big:   { width: 500 , quality: 70}
#                #cinema:     { width: 1850 , quality: 768}
#                #grandmatv:  { width: 640 , quality: 480}
#
#    cdn:
#        server:
#            path: %kernel.http_host%/uploads/media # http://media.sonata-project.org/
#
#        #panther:
#        #    path:       http://domain.pantherportal.com/uploads/media
#        #    site_id:
#        #    password:
#        #    username:
#
#        #fallback:
#        #    master:     sonata.media.cdn.panther
#        #    fallback:   sonata.media.cdn.server
#
#    filesystem:
#        local:
#            directory:  %kernel.root_dir%/../web/uploads/media
#            create:     true
#
#    providers:
#        file:
#            resizer:    false
#            filesystem: sonata.media.filesystem.local
#            cdn:        sonata.media.cdn.server
#            generator:  sonata.media.generator.default
#            thumbnail:  sonata.media.thumbnail.format
#
#        image:
#            resizer:    sonata.media.resizer.square # sonata.media.resizer.simple
#            filesystem: sonata.media.filesystem.local
#            cdn:        sonata.media.cdn.server
#            generator:  sonata.media.generator.default
#            thumbnail:  sonata.media.thumbnail.format
#
#        youtube:
#            resizer:    sonata.media.resizer.simple
#            filesystem: sonata.media.filesystem.local
#            cdn:        sonata.media.cdn.server
#            generator:  sonata.media.generator.default
#            thumbnail:  sonata.media.thumbnail.format
#
#        dailymotion:
#            resizer:    sonata.media.resizer.simple
#            filesystem: sonata.media.filesystem.local
#            cdn:        sonata.media.cdn.server
#            generator:  sonata.media.generator.default
#            thumbnail:  sonata.media.thumbnail.format
#
#        vimeo:
#            resizer:    sonata.media.resizer.simple
#            filesystem: sonata.media.filesystem.local
#            cdn:        sonata.media.cdn.server
#            generator:  sonata.media.generator.default
#            thumbnail:  sonata.media.thumbnail.format
##
## MenuBundle configuration
##
#knp_menu:
#    twig: true  # set to false to disable the Twig extension and the TwigRenderer
#    templating: false # if true, enables the helper for PHP templates
#    default_renderer: twig # The renderer to use, list is also available by default
#
##
## KnpPaginationBundle configuration
##
#knp_paginator:
#    page_range: 5                      # default page range used in pagination control
#    default_options:
#        page_name: page                # page query parameter name
#        sort_field_name: sort          # sort field query parameter name
#        sort_direction_name: direction # sort direction query parameter name
#        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
#    template:
#        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
#        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
#
#knp_snappy:
#    pdf:
#        enabled:    true
#        #binary:     /usr/local/bin/wkhtmltopdf
#        options:    []
#    image:
#        enabled:    true
#        #binary:     /usr/local/bin/wkhtmltoimage
#        options:    []
