#gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery
#
#media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media
#
#pixlr:
#    resource: '@SonataMediaBundle/Resources/config/routing/pixlr.xml'
#    prefix: /
    
#
#   import routes from a controller directory
#
#annotation_gedmo:
#    resource: "@SfynxMediaBundle/Layers/Presentation/Coordination/Mediatheque/Command"
#    type:     annotation
    
#SfynxMediaBundle:Mediatheque
sfynx_media_mediatheque:
    resource: "@SfynxMediaBundle/Resources/config/routing/mediatheque.xml"
    prefix: /admin/gedmo/media