parameters:
    # Manager class
    sfynx.media.manager.mediatheque.entity.class: Sfynx\MediaBundle\Layers\Domain\Service\Mediatheque\Manager\EntityManager
    sfynx.media.manager.mediatheque.params:
        class: '%sfynx.media.mapping.mediatheque.class%'
    # Adapter factory class
    sfynx.media.factory.mediatheque.class: Sfynx\CoreBundle\Layers\Infrastructure\Persistence\Factory\MultiAdapterFactory

    # ORM QueryBuilder names
    sfynx.media.repository.mediatheque.orm.query.querybuilder:
        FindAllByCategoryQueryBuilder: 'Sfynx\MediaBundle\Layers\Infrastructure\Persistence\Adapter\Query\Orm\Mediatheque\QueryBuilder\FindAllByCategoryQueryBuilder'
        FindAllByCategoryQueryTransfomer: 'Sfynx\MediaBundle\Layers\Infrastructure\Persistence\Adapter\Query\Orm\Mediatheque\QueryTransfomer\FindAllByCategoryQueryTransfomer'
    sfynx.media.repository.mediatheque.orm.command.querybuilder: []
    # COUCHDB QueryBuilder names
    sfynx.media.repository.mediatheque.couchdb.query.querybuilder: []
    sfynx.media.repository.mediatheque.couchdb.command.querybuilder: []

services:
    #
    # configuration of the user manager working with Orm, Odm, Couchdb
    #
    sfynx.media.manager.mediatheque.entity:
        class: '%sfynx.media.manager.mediatheque.entity.class%'
        arguments:
            - '@sfynx.media.factory.mediatheque'
        calls:
            - [ setParams, [ '%sfynx.media.manager.mediatheque.params%' ] ]
