parameters:
    # Manager class
    sfynx.media.manager.media.entity.class: Sfynx\MediaBundle\Layers\Domain\Service\Media\Manager\EntityManager
    # Adapter factory class
    sfynx.media.factory.media.class: Sfynx\CoreBundle\Layers\Infrastructure\Persistence\Factory\MultiAdapterFactory
    # Entity class value
    sfynx.media.manager.media.params:
      class: '%sfynx.media.media_class%'
    # Reposioty names
    sfynx.media.repository.media.orm.command.class: Sfynx\MediaBundle\Layers\Infrastructure\Persistence\Adapter\Command\Orm\MediaRepository
    sfynx.media.repository.media.orm.query.class: Sfynx\MediaBundle\Layers\Infrastructure\Persistence\Adapter\Query\Orm\MediaRepository

services:
    #
    # configuration of the user manager working with Orm, Odm, Couchdb
    #
    sfynx.media.manager.media.entity:
        class: '%sfynx.media.manager.media.entity.class%'
        arguments:
            - '@sfynx.media.factory.media'
        calls:
            - [ setParams, [ '%sfynx.media.manager.media.params%' ] ]
