parameters:
    # Manager class
    sfynx.media.manager.media.entity.class: Sfynx\MediaBundle\Layers\Domain\Service\Media\Manager\EntityManager
    sfynx.media.manager.media.params:
        class: '%sfynx.media.mapping.media.class%'
    # Adapter factory class
    sfynx.media.factory.media.class: Sfynx\CoreBundle\Layers\Infrastructure\Persistence\Factory\MultiAdapterFactory

    # ORM QueryBuilder names
    sfynx.media.repository.media.orm.query.querybuilder: []
    sfynx.media.repository.media.orm.command.querybuilder: []
    # COUCHDB QueryBuilder names
    sfynx.media.repository.media.couchdb.query.querybuilder: []
    sfynx.media.repository.media.couchdb.command.querybuilder: []

services:
    #
    # configuration of the user manager working with Orm, Odm, Couchdb
    #
    sfynx.media.manager.media.entity:
        class: '%sfynx.media.manager.media.entity.class%'
        arguments:
            - '@sfynx.media.factory.media'
        calls:
            - [ setParams, [ '%sfynx.media.manager.media.params%' ] ]
