parameters:
    sfynx.media.event_subscriber.storage.handler.class: Sfynx\MediaBundle\Layers\Domain\EventSubscriber\StorageProviderHandler
    sfynx.media.securing.signed.urls.class: Sfynx\MediaBundle\Layers\Domain\Service\Token\TokenService

services:
    #
    # configuration of the event subscriber of entities
    #
    sfynx.media.event_subscriber.storage.handler:
        class: '%sfynx.media.event_subscriber.storage.handler.class%'
        public: false
        arguments:
            - '%sfynx.media.storage.provider%'
            - '@service_container'
        tags:
            - { name: doctrine.event_subscriber }

    sfynx.media.storage_provider.api_media:
        class: 'Sfynx\MediaBundle\Layers\Domain\Service\StorageProvider\ApiMediaStorageProvider'
        public: true
        arguments:
            - '@sfynx_rest_client.api.media'
        tags:
            - { name: sfynx_media.storage_provider, alias: Sfynx Media }

    #
    # configuration of the JWT services
    #
    sfynx.media.securing.signed.urls:
        class: '%sfynx.media.securing.signed.urls.class%'
        arguments:
           - "@lexik_jwt_authentication.encoder.default"
           - "@lexik_jwt_authentication.key_loader.raw"
           - '@sfynx.core.request.strategy'
           - '@security.token_storage'
           - { start: 0, expire: 3600, unique: false}
